### ISSUE TITLE
Cannot rebuild

### ISSUE THREAD

**Issue by tomeroto** [visjs/vis-graph3d#177]
Hi,

I can rebuild script using command "npm run build". I was follow instructions step by step.

This is output from terminal:

```
> vis-graph3d@0.0.0-no-version build E:\js\vis-graph3d
> npm run js:graph3d


> vis-graph3d@0.0.0-no-version js:graph3d E:\js\vis-graph3d
> rollup --config rollup.build.js && rollup --config rollup.config.js

[!] Error: Cannot find module 'vis-dev-utils'
Require stack:
- E:\js\vis-graph3d\rollup.build.js
- C:\Users\Acer\AppData\Roaming\npm\node_modules\rollup\dist\shared\loadConfigFile.js
- C:\Users\Acer\AppData\Roaming\npm\node_modules\rollup\dist\bin\rollup
Error: Cannot find module 'vis-dev-utils'
Require stack:
- E:\js\vis-graph3d\rollup.build.js
- C:\Users\Acer\AppData\Roaming\npm\node_modules\rollup\dist\shared\loadConfigFile.js
- C:\Users\Acer\AppData\Roaming\npm\node_modules\rollup\dist\bin\rollup
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (E:\js\vis-graph3d\rollup.build.js:8:19)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.require.extensions.<computed> [as .js] (C:\Users\Acer\AppData\Roaming\npm\node_modules\rollup\dist\shared\loadConfigFile.js:516:20)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vis-graph3d@0.0.0-no-version js:graph3d: `rollup --config rollup.build.js && rollup --config rollup.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vis-graph3d@0.0.0-no-version js:graph3d script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Acer\AppData\Roaming\npm-cache\_logs\2020-05-02T13_06_22_336Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vis-graph3d@0.0.0-no-version build: `npm run js:graph3d`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vis-graph3d@0.0.0-no-version build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Acer\AppData\Roaming\npm-cache\_logs\2020-05-02T13_06_22_527Z-debug.log
```

My environtments:
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest

**Comment by Thomaash** [comment]
Could you provide some more info? I tried building on Windows 10 and it went fine (except for corrupted color output). Node version? Npm version?

It seems to me that there's something fishy about the imports. AFAIK everything should be contained within the local node_modules in the project but your log talks about `C:\Users\Acer\AppData\Roaming\npm\node_modules`. Do you have all dependencies installed properly (`npm ci`)?

**Comment by tomeroto** [comment]
Ok thank you for your information. After updated node and npm, it works!

**Comment by tomeroto** [comment]
Hello,

**Comment by tomeroto** [comment]
Hello,

After build I found errors when run examples.

```
Uncaught TypeError: no is not a function
    at fails.js:5
    at vis-graph3d.min.js:26
    at vis-graph3d.min.js:26
Uncaught TypeError: vis.DataSet is not a constructor
    at getDataCsv (playground.js:315)
    at drawCsv (playground.js:461)
    at loadCsvExample (playground.js:59)
    at load (playground.js:8)
    at onload (index.html:22)
Uncaught TypeError: vis.DataSet is not a constructor
    at getDataCsv (playground.js:315)
    at drawCsv (playground.js:461)
    at draw (playground.js:455)
    at HTMLInputElement.onclick (index.html:66)
```

I just rebuid not modified any code.

**Comment by Thomaash** [comment]
I encountered this too. It happens only on Windows. So build on Linux/Mac? I'm sorry, this is far from ideal solution but I don't know why it happens or how to fix it. Sadly I don't have the time to properly debug it right now (and probably won't have for at least a few weeks).

Maybe try downgrading Graph3D commit by commit to pin point which commit introduced this issue. That should narrow down the potential causes and make it easier to fix.
